CREATE TABLE IF NOT EXISTS `canciones` (
  `id` INT(11) NOT NULL,  
  `url_yt` VARCHAR(255) NOT NULL,
  `video_id` VARCHAR(100) NOT NULL,
  `title` VARCHAR(100) NOT NULL,
  `artist` VARCHAR(100) NOT NULL,
  `album` VARCHAR(100) NOT NULL,
  `duration` VARCHAR(20) NOT NULL,
  `year` INT(10) NOT NULL,
  `image_path` VARCHAR(255) NOT NULL,
  `downloaded` TINYINT(1) NOT NULL,
  `fecha_publish` DATETIME DEFAULT NULL,
  `creado` DATETIME DEFAULT NULL,
  `modificado` DATETIME DEFAULT NULL,  
  `genre` VARCHAR(50) NOT NULL,
  `filesize` VARCHAR(15) NOT NULL,
  `sample_rate` INT(50) NOT NULL,
  `bitrate` INT(50) NOT NULL,
  `dataformat` VARCHAR(15) NOT NULL,
  `quality` VARCHAR(50) NOT NULL,
  `url_yt_download` VARCHAR(255) NOT NULL,
  `filename` VARCHAR(255) NOT NULL
) ENGINE=INNODB AUTO_INCREMENT=301665 DEFAULT CHARSET=utf8;